### ISSUE TITLE
usage example

### ISSUE THREAD

**Issue by caozhenxiang** [ermshaua/classification-score-stream#2]
Can you provide a usage example for the ClaSS approach? All notebooks included only directly call the .csv files. It is very hard to understand how to use this implementation on new data. Thank you.

**Comment by ermshaua** [comment]
Hi!

Sure! Please have a look at: https://github.com/ermshaua/classification-score-stream/blob/main/benchmark/simple_test.py In this test, I show how to run ClaSS using a simple example. Basically, the API is:

`
from src.clazz.segmentation import ClaSS
stream = ClaSS()

while sensor.has_value():
    stream.update(sensor.get_value())
    # check stream.change_points for CPs
`

Best regards
Arik
